"""Tests for VerilogEmitter: case/endcase, register locals, header, constant folding."""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
import ast
import unittest
from veripy import Module, Input, Output, Register, Signal
from veripy.emit_verilog import VerilogEmitter


# --- Modules used by tests ---

class Mux4(Module):
    """if/elif/else chain on one signal → should emit case/endcase."""
    def __init__(self):
        self.sel = Input(2)
        self.a   = Input(8)
        self.b   = Input(8)
        self.c   = Input(8)
        self.d   = Input(8)
        self.out = Output(8)
        super().__init__()

        @self.comb
        def select():
            if self.sel == 0:
                self.out = self.a
            elif self.sel == 1:
                self.out = self.b
            elif self.sel == 2:
                self.out = self.c
            else:
                self.out = self.d


class RegLocalModule(Module):
    """Uses a Register local inside an always block."""
    def __init__(self):
        self.clk = Input()
        self.d   = Input(8)
        self.q   = Output(8)
        self.r   = Register(8)
        super().__init__()

        @self.comb
        def drive():
            self.q = self.r

        @self.posedge(self.clk)
        def logic():
            tmp = Register(8)
            tmp = self.d + 1
            self.r = tmp


class ParamModule(Module):
    """Parameterized module for header/param tests."""
    def __init__(self, width=8):
        self.a   = Input(width)
        self.b   = Output(width)
        super().__init__()

        @self.comb
        def drive():
            self.b = self.a


# --- Test classes ---

class TestCaseEmission(unittest.TestCase):
    def setUp(self):
        self.v = Mux4().to_verilog()

    def test_case_keyword_present(self):
        self.assertIn('case (sel)', self.v)

    def test_endcase_present(self):
        self.assertIn('endcase', self.v)

    def test_case_labels(self):
        self.assertIn('0: begin', self.v)
        self.assertIn('1: begin', self.v)
        self.assertIn('2: begin', self.v)

    def test_default_branch(self):
        self.assertIn('default: begin', self.v)

    def test_no_if_elif_chain(self):
        # The if/elif chain should be replaced by case, not emitted as if/else
        lines = self.v.split('\n')
        # Count 'if (sel ==' — should be zero since it became a case
        if_sel_lines = [l for l in lines if 'if (sel ==' in l]
        self.assertEqual(len(if_sel_lines), 0)


class TestRegLocals(unittest.TestCase):
    def setUp(self):
        self.v = RegLocalModule().to_verilog()

    def test_reg_declaration_emitted(self):
        self.assertIn('reg [7:0] tmp;', self.v)

    def test_blocking_assign(self):
        # Register locals use blocking assign (=) not NBA (<=)
        self.assertIn('tmp = (d + 1);', self.v)

    def test_nba_for_module_register(self):
        # Module-level register still uses <=
        self.assertIn('r <= tmp;', self.v)


class TestAutoHeader(unittest.TestCase):
    def test_cli_header_format(self):
        # The header is added by cmd_build, not by emit(). Test the format.
        from veripy.cli import cmd_build
        import types
        # Simulate what cmd_build does: emit + prepend header
        m = ParamModule(width=4)
        emitter = VerilogEmitter(m, 'param_module')
        src = emitter.emit()
        header = f"// Auto-generated by veripy from test.py — do not edit\n"
        full = header + src
        self.assertTrue(full.startswith('// Auto-generated by veripy'))
        self.assertIn('do not edit', full)

    def test_emit_has_module_declaration(self):
        v = ParamModule(width=4).to_verilog()
        self.assertIn('module parammodule', v)
        self.assertIn('endmodule', v)


class TestConstantFolding(unittest.TestCase):
    def setUp(self):
        self.emitter = VerilogEmitter(ParamModule(width=4), 'test')

    def _fold(self, op_cls, left, right):
        node = ast.BinOp(
            left=ast.Constant(value=left),
            op=op_cls(),
            right=ast.Constant(value=right),
        )
        return self.emitter._try_fold(node)

    def test_fold_add(self):
        r = self._fold(ast.Add, 3, 4)
        self.assertEqual(r.value, 7)

    def test_fold_sub(self):
        r = self._fold(ast.Sub, 10, 3)
        self.assertEqual(r.value, 7)

    def test_fold_mult(self):
        r = self._fold(ast.Mult, 3, 4)
        self.assertEqual(r.value, 12)

    def test_fold_lshift(self):
        r = self._fold(ast.LShift, 1, 4)
        self.assertEqual(r.value, 16)

    def test_fold_rshift(self):
        r = self._fold(ast.RShift, 16, 2)
        self.assertEqual(r.value, 4)

    def test_fold_bitand(self):
        r = self._fold(ast.BitAnd, 0xFF, 0x0F)
        self.assertEqual(r.value, 0x0F)

    def test_fold_bitor(self):
        r = self._fold(ast.BitOr, 0xA0, 0x0B)
        self.assertEqual(r.value, 0xAB)

    def test_no_fold_non_constant(self):
        node = ast.BinOp(
            left=ast.Name(id='x'),
            op=ast.Add(),
            right=ast.Constant(value=1),
        )
        self.assertIsNone(self.emitter._try_fold(node))


class TestSubmoduleParamOverride(unittest.TestCase):
    def test_param_override_on_instance(self):
        """Sub-modules with _params emit #(.param(value)) on the instance."""
        class Inner(Module):
            def __init__(self, size=1024):
                self.d = Input(8)
                self.q = Output(8)
                super().__init__()
                @self.comb
                def drive():
                    self.q = self.d

        class Outer(Module):
            def __init__(self):
                self.d = Input(8)
                self.q = Output(8)
                self.a = Inner(size=1024)
                self.a._params = {'size': 1024}
                self.b = Inner(size=4096)
                self.b._params = {'size': 4096}
                super().__init__()
                @self.comb
                def wire():
                    self.a.d = self.d
                    self.b.d = self.d
                    self.q = self.a.q

        v = VerilogEmitter(Outer(), 'outer').emit()
        self.assertIn('#(.size(1024)) a', v)
        self.assertIn('#(.size(4096)) b', v)

    def test_no_params_no_hash(self):
        """Sub-modules without _params emit plain instance."""
        from examples.datapath import Datapath
        v = VerilogEmitter(Datapath(), 'datapath').emit()
        # With auto-capture, ALU gets _params from its constructor
        self.assertIn('#(.width(16)) alu', v)


class TestParamHeader(unittest.TestCase):
    def test_param_in_header(self):
        m = ParamModule(width=16)
        m._params = {'width': 16}
        v = m.to_verilog()
        self.assertIn('parameter width = 16', v)
        self.assertIn('#(', v)

    def test_no_param_no_hash(self):
        m = ParamModule(width=8)
        m._params = {}  # explicitly clear to suppress parameter header
        v = m.to_verilog()
        self.assertNotIn('#(', v)


if __name__ == '__main__':
    unittest.main()
