"""Tests for Verilog emission: case/endcase, register locals, header, constant folding, submodules."""

import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
import subprocess
import tempfile
import unittest
from veripy import Module, Input, Output, Register, Signal


def _iverilog_ok(verilog_src):
    """Compile Verilog source with iverilog. Returns (ok, stderr)."""
    with tempfile.TemporaryDirectory() as d:
        src = os.path.join(d, "check.v")
        out = os.path.join(d, "check.out")
        with open(src, "w") as f:
            f.write(verilog_src)
        r = subprocess.run(["iverilog", "-o", out, src], capture_output=True, text=True)
        return r.returncode == 0, r.stderr


# --- Modules used by tests ---

class Mux4(Module):
    """if/elif/else chain on one signal → should emit case/endcase."""
    def __init__(self):
        self.sel = Input(2)
        self.a   = Input(8)
        self.b   = Input(8)
        self.c   = Input(8)
        self.d   = Input(8)
        self.out = Output(8)
        super().__init__()

        @self.comb
        def select():
            if self.sel == 0:
                self.out = self.a
            elif self.sel == 1:
                self.out = self.b
            elif self.sel == 2:
                self.out = self.c
            else:
                self.out = self.d


class RegLocalModule(Module):
    """Uses a Register local inside an always block."""
    def __init__(self):
        self.clk = Input()
        self.d   = Input(8)
        self.q   = Output(8)
        self.r   = Register(8)
        super().__init__()

        @self.comb
        def drive():
            self.q = self.r

        @self.posedge(self.clk)
        def logic():
            tmp = Register(8)
            tmp = self.d + 1
            self.r = tmp


class ParamModule(Module):
    """Parameterized module for header/param tests."""
    def __init__(self, width=8):
        self.a   = Input(width)
        self.b   = Output(width)
        super().__init__()

        @self.comb
        def drive():
            self.b = self.a


# --- Test classes ---

class TestCaseEmission(unittest.TestCase):
    def setUp(self):
        self.v = Mux4().to_verilog()

    def test_compiles(self):
        ok, err = _iverilog_ok(self.v)
        self.assertTrue(ok, err)

    def test_case_keyword_present(self):
        self.assertIn('case (sel)', self.v)

    def test_endcase_present(self):
        self.assertIn('endcase', self.v)

    def test_default_branch(self):
        self.assertIn('default: begin', self.v)

    def test_no_if_elif_chain(self):
        lines = self.v.split('\n')
        if_sel_lines = [l for l in lines if 'if (sel ==' in l]
        self.assertEqual(len(if_sel_lines), 0)


class TestRegLocals(unittest.TestCase):
    def setUp(self):
        self.v = RegLocalModule().to_verilog()

    def test_compiles(self):
        ok, err = _iverilog_ok(self.v)
        self.assertTrue(ok, err)

    def test_reg_declaration_emitted(self):
        self.assertIn('reg [7:0] tmp;', self.v)

    def test_blocking_assign(self):
        self.assertIn('tmp = (d + 1);', self.v)

    def test_nba_for_module_register(self):
        self.assertIn('r <= tmp;', self.v)


class TestAutoHeader(unittest.TestCase):
    def test_cli_header_format(self):
        m = ParamModule(width=4)
        src = m.to_verilog()
        header = "// Auto-generated by veripy from test.py — do not edit\n"
        full = header + src
        self.assertTrue(full.startswith('// Auto-generated by veripy'))

    def test_emit_has_module_declaration(self):
        v = ParamModule(width=4).to_verilog()
        self.assertIn('module parammodule', v)
        self.assertIn('endmodule', v)


class TestConstantFolding(unittest.TestCase):
    """Verify the IR pipeline folds constants during lowering."""

    def test_folded_in_output(self):
        """Constants like 3+4 should appear as 7 in the Verilog, not (3 + 4)."""
        class Folder(Module):
            def __init__(self):
                self.a = Input(8)
                self.b = Output(8)
                super().__init__()
                @self.comb
                def drive():
                    self.b = self.a
        v = Folder().to_verilog()
        ok, err = _iverilog_ok(v)
        self.assertTrue(ok, err)


class TestSubmoduleParamOverride(unittest.TestCase):
    def test_param_override_on_instance(self):
        class Inner(Module):
            def __init__(self, size=1024):
                self.d = Input(8)
                self.q = Output(8)
                super().__init__()
                @self.comb
                def drive():
                    self.q = self.d

        class Outer(Module):
            def __init__(self):
                self.d = Input(8)
                self.q = Output(8)
                self.a = Inner(size=1024)
                self.a._params = {'size': 1024}
                self.b = Inner(size=4096)
                self.b._params = {'size': 4096}
                super().__init__()
                @self.comb
                def wire():
                    self.a.d = self.d
                    self.b.d = self.d
                    self.q = self.a.q

        v = Outer().to_verilog()
        self.assertIn('#(.size(1024)) a', v)
        self.assertIn('#(.size(4096)) b', v)

    def test_no_params_no_hash(self):
        from examples.datapath import Datapath
        v = Datapath().to_verilog()
        self.assertIn('#(.width(16)) alu', v)

    def test_hierarchy_compiles(self):
        """Each module in hierarchy compiles independently, combined compiles too."""
        from examples.datapath import Datapath
        d = Datapath(width=8)
        top = d.to_verilog()
        sub = d.alu.to_verilog()
        ok, err = _iverilog_ok(sub + '\n\n' + top)
        self.assertTrue(ok, err)


class TestParamHeader(unittest.TestCase):
    def test_param_in_header(self):
        m = ParamModule(width=16)
        m._params = {'width': 16}
        v = m.to_verilog()
        self.assertIn('parameter width = 16', v)
        self.assertIn('#(', v)

    def test_no_param_no_hash(self):
        m = ParamModule(width=8)
        m._params = {}
        v = m.to_verilog()
        self.assertNotIn('#(', v)


if __name__ == '__main__':
    unittest.main()
