"""veripy CLI — build Verilog from Python modules, run dual-path tests."""

import argparse
import importlib.util
import inspect
import os
import subprocess
import sys
import tempfile
import unittest

import re

from .module import Module
from .emit_verilog import VerilogEmitter, _to_snake


def _load_modules(path, module_name=None, params=None):
    """Import a Python file and return [(name, instance)] of Module subclasses or @module factories."""
    parent_dir = os.path.dirname(os.path.abspath(path))
    if parent_dir not in sys.path:
        sys.path.insert(0, parent_dir)
    spec = importlib.util.spec_from_file_location("_user_module", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    params = params or {}
    results = []

    # Class-based modules
    for name, cls in inspect.getmembers(mod, inspect.isclass):
        if not (issubclass(cls, Module) and cls is not Module):
            continue
        if module_name and name != module_name:
            continue
        sig = inspect.signature(cls.__init__)
        kwargs = {pname: int(params[pname]) for pname in sig.parameters
                  if pname != 'self' and pname in params}
        results.append((name, cls(**kwargs)))

    # @module factory functions
    for name, obj in vars(mod).items():
        if not getattr(obj, '_is_veripy_module', False):
            continue
        if module_name and name != module_name:
            continue
        kwargs = {k: int(params[k]) for k in obj._param_names if k in params}
        results.append((name, obj(**kwargs)))

    if module_name and not results:
        sys.exit(f"error: no module named '{module_name}' in {path}")
    return results


def _compile_verilog(verilog_src):
    """Compile Verilog source with iverilog. Returns (ok, stderr)."""
    with tempfile.TemporaryDirectory() as tmpdir:
        src_f = os.path.join(tmpdir, "check.v")
        out_f = os.path.join(tmpdir, "check.out")
        with open(src_f, "w") as f:
            f.write(verilog_src)
        r = subprocess.run(
            ["iverilog", "-o", out_f, src_f],
            capture_output=True, text=True,
        )
        return r.returncode == 0, r.stderr


def _parse_params(raw):
    """Parse ['n=4', 'w=8'] into {'n': '4', 'w': '8'}."""
    params = {}
    for item in (raw or []):
        if "=" not in item:
            sys.exit(f"error: bad --param format '{item}', expected key=value")
        k, v = item.split("=", 1)
        params[k] = v
    return params


def cmd_build(args):
    params = _parse_params(args.param)
    modules = _load_modules(args.file, module_name=args.module, params=params)
    if not modules:
        sys.exit(f"error: no modules found in {args.file}")

    all_modules = []  # [(snake_name, verilog_src)]
    seen = set()

    def _collect(mod, mod_name):
        if mod_name in seen:
            return
        seen.add(mod_name)
        for sub_name, sub in mod._submodules().items():
            sub_snake = _to_snake(type(sub).__name__)
            factory = getattr(type(sub), '_veripy_factory', None)
            fresh = factory() if factory else type(sub)()
            _collect(fresh, sub_snake)
        e = VerilogEmitter(mod, mod_name)
        all_modules.append((mod_name, e.emit()))

    for name, instance in modules:
        _collect(instance, _to_snake(name))

    # Compile-check all files together
    combined = '\n\n'.join(src for _, src in all_modules)
    ok, stderr = _compile_verilog(combined)
    if not ok:
        print("error: iverilog compilation failed:", file=sys.stderr)
        print(stderr, file=sys.stderr)
        sys.exit(1)

    header = f"// Auto-generated by veripy from {os.path.basename(args.file)} — do not edit\n"

    if args.output:
        os.makedirs(args.output, exist_ok=True)
        for mod_name, src in all_modules:
            out_path = os.path.join(args.output, f"{mod_name}.v")
            with open(out_path, "w") as f:
                f.write(header + src)
            print(f"  {out_path}")
    else:
        print(header + combined)


def cmd_test(args):
    argv = ["python", "-m", "unittest"]
    if args.path:
        argv += ["discover", "-s", args.path, "-p", "test_*.py"]
    else:
        argv += ["discover", "-p", "test_*.py"]
    if args.verbose:
        argv.append("-v")
    sys.exit(subprocess.run(argv).returncode)


def cmd_import(args):
    import os
    path = args.file
    if os.path.isdir(path):
        from .import_verilog import import_project
        if not args.output:
            print("Error: -o <output_dir> is required when importing a directory", file=sys.stderr)
            sys.exit(1)
        result = import_project(path)
        for rel_py, source in sorted(result.items()):
            out_path = os.path.join(args.output, rel_py)
            os.makedirs(os.path.dirname(out_path) or '.', exist_ok=True)
            with open(out_path, 'w') as f:
                f.write(source)
            print(f"Wrote {out_path}")
        # Write __init__.py files for each directory
        for root, dirs, _files in os.walk(args.output):
            init = os.path.join(root, '__init__.py')
            if not os.path.exists(init):
                open(init, 'w').close()
    else:
        from .import_verilog import import_verilog
        with open(path) as f:
            src = f.read()
        python_src = import_verilog(src)
        if args.output:
            with open(args.output, 'w') as f:
                f.write(python_src)
            print(f"Wrote {args.output}")
        else:
            print(python_src)


def cmd_lint(args):
    from .lint import lint
    modules = _load_modules(args.file, module_name=args.module)
    if not modules:
        sys.exit(f"error: no modules found in {args.file}")
    found = False
    for name, instance in modules:
        warnings = lint(instance)
        if warnings:
            found = True
            for level, msg in warnings:
                print(f"{name}: [{level}] {msg}")
    if not found:
        print("No issues found.")
    sys.exit(1 if found else 0)


def main():
    parser = argparse.ArgumentParser(prog="veripy", description="VeriPy HDL toolchain")
    sub = parser.add_subparsers(dest="command", required=True)

    # build
    p_build = sub.add_parser("build", help="Emit and compile-check Verilog from a Python module")
    p_build.add_argument("file", help="Python file containing Module subclass(es)")
    p_build.add_argument("-o", "--output", help="Output directory for .v files (default: stdout)")
    p_build.add_argument("-m", "--module", help="Target a specific Module subclass by name")
    p_build.add_argument("-p", "--param", action="append", help="Module parameter (e.g. -p n=4)")

    # test
    p_test = sub.add_parser("test", help="Run dual-path VeripyTestCase suite")
    p_test.add_argument("path", nargs="?", help="Test file or directory (default: discover)")
    p_test.add_argument("-v", "--verbose", action="store_true")

    # import
    p_import = sub.add_parser("import", help="Convert Verilog to VeriPy Python")
    p_import.add_argument("file", help="Verilog file or directory to convert")
    p_import.add_argument("-o", "--output", help="Output file (single .v) or directory (project import)")

    # lint
    p_lint = sub.add_parser("lint", help="Run static checks on a VeriPy module")
    p_lint.add_argument("file", help="Python file containing Module subclass(es)")
    p_lint.add_argument("-m", "--module", help="Target a specific Module subclass by name")

    args = parser.parse_args()
    {"build": cmd_build, "test": cmd_test, "import": cmd_import, "lint": cmd_lint}[args.command](args)


if __name__ == "__main__":
    main()
