"""Project: tracks modules and provides dependency-ordered file lists."""

import os
import re
from .module import Module


def _to_snake(name):
    return re.sub(r'(?<=[a-z0-9])(?=[A-Z])', '_', name).lower()


class Project:
    """Tracks modules and their sub-module dependencies.

    Provides dependency-ordered module lists for build tools.
    BlackBox modules are excluded (their definitions come from vendor libs).

    Usage::

        proj = Project()
        proj.add(top_module)
        proj.write('build/')
        print(proj.to_vivado_tcl('build/'))
    """

    def __init__(self):
        self._tops = []  # [(name, module)]

    def add(self, module, name=None):
        """Add a top-level module to the project."""
        if name is None:
            name = _to_snake(type(module).__name__)
        self._tops.append((name, module))
        return self

    def modules(self):
        """Return all modules in dependency order (leaves first).

        BlackBox modules are excluded.
        """
        ordered = []
        seen = set()

        def _walk(mod, mod_name):
            if mod_name in seen:
                return
            seen.add(mod_name)
            for _sub_attr, sub in mod._submodules().items():
                if getattr(sub, '_is_blackbox', False):
                    continue
                sub_snake = _to_snake(type(sub).__name__)
                factory = getattr(type(sub), '_veripy_factory', None)
                fresh = factory() if factory else type(sub)()
                _walk(fresh, sub_snake)
            ordered.append((mod_name, mod))

        for name, mod in self._tops:
            _walk(mod, name)

        return ordered

    def file_list(self):
        """Return dependency-ordered ``(name, verilog_source)`` pairs."""
        return [(name, mod.to_verilog(name)) for name, mod in self.modules()]

    def write(self, output_dir):
        """Write all Verilog files to *output_dir* in dependency order.

        Returns list of written file paths.
        """
        os.makedirs(output_dir, exist_ok=True)
        paths = []
        for name, src in self.file_list():
            p = os.path.join(output_dir, f'{name}.v')
            with open(p, 'w') as f:
                f.write(src)
            paths.append(p)
        return paths

    def _file_names(self, output_dir):
        return [f'{output_dir}/{name}.v' for name, _ in self.file_list()]

    def _top_name(self):
        return self._tops[-1][0] if self._tops else None

    # ── Tcl generation ───────────────────────────────────────────────

    def to_vivado_tcl(self, output_dir='rtl'):
        """Generate Vivado Tcl script to read all Verilog files."""
        lines = ['# Auto-generated by VeriPy — Vivado project script']
        for f in self._file_names(output_dir):
            lines.append(f'read_verilog {f}')
        top = self._top_name()
        if top:
            lines.append(f'set_property top {top} [current_fileset]')
        return '\n'.join(lines) + '\n'

    def to_quartus_tcl(self, output_dir='rtl'):
        """Generate Quartus Tcl script to add all Verilog files."""
        lines = ['# Auto-generated by VeriPy — Quartus project script']
        for f in self._file_names(output_dir):
            lines.append(
                f'set_global_assignment -name VERILOG_FILE {f}')
        top = self._top_name()
        if top:
            lines.append(
                f'set_global_assignment -name TOP_LEVEL_ENTITY {top}')
        return '\n'.join(lines) + '\n'

    def to_dc_tcl(self, output_dir='rtl'):
        """Generate Design Compiler Tcl script to read all Verilog files."""
        lines = ['# Auto-generated by VeriPy — Design Compiler script']
        for f in self._file_names(output_dir):
            lines.append(f'analyze -format verilog {f}')
        top = self._top_name()
        if top:
            lines.append(f'elaborate {top}')
        return '\n'.join(lines) + '\n'
